### ISSUE TITLE
BottomSheetViewController Class not open :'(

### ISSUE THREAD

**Issue by HelieDeBPragmaInfodev** [havebeenfitz/AnchoredBottomSheet#3]
Hey mate, thanks for the framework it works very well, but as you may know class of your frameworks that are not declared as open can't be subclassed :'(
Is there any reason why BottomSheetViewController class is declared in public and not in open way ? (Because we can't subclass it now... :/)

**Comment by havebeenfitz** [comment]
Hey, I just had no use case for making it open. What do you need to override? I could make some methods open for example. Making the whole `BottomSheetViewController` `open` may allow you to break things I guess)
